---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: ensure runtime executable is in fact executable
      command: /usr/local/bin/dotnet --info
      register: dotnet_runtime_test_output
    - debug:
        msg: '{{ dotnet_runtime_test_output.stdout }}'
