---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/dotnet --info
      register: dotnet_runtime_test_output
    - name: dotnet --info
      debug:
        msg: '{{ dotnet_runtime_test_output.stdout }}'
